### PR TITLE
Display MARC 795 values and link to subject search

### LINKED ISSUE #3150: Phase 1 to display the MARC 795
This is the first phase of an effort to display the MARC 795 tag, containing Collection Name for physical collections. More information about the effort can be found in: https://github.com/sul-dlss/SearchWorks/issues/3027

Steps identified include:

- [x] 1. Add the 795 ($a and $p) to the Subject index (since public services staff are accustomed to the collection name being there)
- [x] 2. Add the 795 ($a and $p) to the display in search results. Use label "Collection". If the record also has a Finding add or link to a digital collection, place the 795 below the Finding Aid link or the digital collection link.
- [x] 3. IF there are multiple 795 on the same record, display up to two on the results page. Use "more" if there are more than two. Show all the 795s on the record page.
- [x] 4. Change label used for digital collections in search results to "Digital collection" (currently just "Collection")
- [x] 5. In the record view, move the display of the 795 to the top of the record - near Title, Responsibility, Imprint, and Series.
- [x] 6. Hyperlink the 795 ($a and $p) collection name in both the search results and record view, continuing to use the Subject term index.

**Example records** 
Example record: [Poetry](https://searchworks.stanford.edu/view/374067)
Example record with multiple 795 tags: [Asian American review](https://searchworks.stanford.edu/view/5528103)
Example record with 795$p: [Gedanken zu Führungen durch das Goetheanum in Dornach ; Das Ruhrgebiet im Erlebnisfeld der Geschichte](https://searchworks.stanford.edu/view/3441645)
Example records with both physical and digital collections on the same record: [City of San Diego](https://searchworks.stanford.edu/view/11878116) and [Jesús Lara [sound recording] : poesía y prosa](https://searchworks.stanford.edu/view/4416852) and [Robert Creeley Papers](https://searchworks.stanford.edu/view/4084039)

Metadata documentation on use of the 795 field: https://consul.stanford.edu/display/MD/Collection+name+in+SUL+catalog+records

### PR DESCRIPTION
**Pull request by corylown**
Closes #3150 

Show view with vernacular title:
Screenshot 2023-06-29 at 9 07 50 AM

Index view with more/less widget:
Screenshot 2023-06-29 at 9 08 33 AM

Still todo:

- [x] Get truncation more/less working in the results view for linked collection titles.
- [x] Figure out why [_marc_upper_metadata_items.html.erb_spec.rb](https://github.com/sul-dlss/SearchWorks/compare/3150-display-795?expand=1#diff-278e14b00de42b6f5adda6cacdebd783cf5e8c1e122b109a775332dbd94282be) is complaining about no matching route.

### CODE REVIEW

**Comment by thatbudakguy** [comment]
@corylown could you paste the catkeys for the two records shown in the screenshots here, for testing?

**Comment by corylown** [comment]
@thatbudakguy sure!

Example records
Example record: [Poetry](https://searchworks.stanford.edu/view/374067)
Example record with multiple 795 tags: [Asian American review](https://searchworks.stanford.edu/view/5528103)
Example record with 795$p: [Gedanken zu Führungen durch das Goetheanum in Dornach ; Das Ruhrgebiet im Erlebnisfeld der Geschichte](https://searchworks.stanford.edu/view/3441645)
Example records with both physical and digital collections on the same record: [City of San Diego](https://searchworks.stanford.edu/view/11878116) and [Jesús Lara [sound recording] : poesía y prosa](https://searchworks.stanford.edu/view/4416852) and [Robert Creeley Papers](https://searchworks.stanford.edu/view/4084039)

**Review by thatbudakguy — APPROVED** [review]
tried this out with the linked records and everything looked great. the only weirdness was that for catkey 7682065 (the vernacular collection title), clicking the title to do a faceted search resulted in 1 more result for the vernacular version over the english one (182 results vs 181). guessing this is just a data problem though (maybe one record has a typo in the english title, but the chinese is fine)?

**Comment by corylown** [comment]
@thatbudakguy yeah -- I'd guess one of the transliterated strings is different in some way.

**Pull request merged**
