### PR TITLE
update link in alert info to be accessible

### LINKED ISSUE #4125: fix feedback form contrast error
Screenshot 2024-03-12 at 1 50 30 PM

### PR DESCRIPTION
**Pull request by dnoneill**
closes #4125

### CODE REVIEW

**Comment by jcoyne** [comment]
@dnoneill can you explain what "in line with bootstrap" means?

**Comment by dnoneill** [comment]
We override the color for alert-info with this line https://github.com/sul-dlss/SearchWorks/blob/7c5bc1f741cfa45ab231e5dfa4b82b5db26fd480/app/assets/stylesheets/base.scss#L20 so this is just overriding our override so that the color is being set from bootstrap.

**Comment by jcoyne** [comment]
@dnoneill that's a `text-decoration-color`, not a `color`

**Comment by jcoyne** [comment]
Have you considered using the `.alert-link`style provided by BS? https://getbootstrap.com/docs/4.6/components/alerts/#link-color

**Comment by dnoneill** [comment]
Sorry I was thinking of something else. 
I think that might be a question for @dbranchini. We definitely could use digital_blue_dark. It does not cause a contrast error.

I did look at .alert-link. I did not think it looked very good. (see attached screenshot)
Screenshot 2024-03-14 at 1 41 02 PM

**Comment by jcoyne** [comment]
@dnoneill if we use alert-link, we may need to override some styles for it, but it's a good descriptive class name anyway and it's purpose is documented.

**Comment by dnoneill** [comment]
That seems like a lot of css changes so we can include a class that we are going to strip most of the css out of.

**Comment by jcoyne** [comment]
@dnoneill the only css change would be to change the font weight which is a Bootstrap config variable.

**Comment by dnoneill** [comment]
and I guess column wouldn't have to adjust column size because once the bold is removed it is fine. Okay. Let's go with that.

**Review by jcoyne — APPROVED** [review]

**Pull request merged**
