### PR TITLE
Restructure the banner into a red search bar and a grey navbar

### LINKED ISSUE #1396: Banner modifications
Note that this affects all of SearchWorks, not just Article search.

Before
screen shot 2017-06-23 at 4 59 42 pm

After
screen shot 2017-06-23 at 4 56 05 pm

### make the red banner 100px high
- [x] vertically center the SearchWorks logo, catalog/article selector, and search box
- [x] change the catalog/article font to the default (open sans, light)

### add grey navbar below the red banner
- [x] navbar is 35px high
- [x] background color is #857e74
- [x] move `box-shadow: 0 4px 8px -2px rgba(0,0,0,0.2)` from `#search-navbar-container` to the grey navbar

### move the #searchbar-topnav-menu menu from the white topnav to the left side of the grey navbar
- [x] label the menu "Library services"
- [x] remove the sr-only text

### move the advanced/browse/selections options from the red banner to the right side of the grey navbar
- [x] their collapse behaviour moves down here as well
- [x] remove their icons
- [x] menu text is:
```
color: #fff;
font-size: 22px;
font-size: 1.375rem;
font-weight: 100;
line-height: 35px;
padding: 0 24px;
```

[pulled mobile stuff into another ticket]

### PR DESCRIPTION
**Pull request by drh-stanford**
This PR fixes #1396.  I will deploy this branch to the sandbox for testing.

Notes for things that do not work:

- [x] Left alignment for the gray bar is static :(
- [x] FIXED: White background flashes when closing pulldowns on the gray bar
- [x] FIXED: Tab focus doesn't highlight the 2 pulldowns in the gray bar (Library services, Selections)

banner mov

### CODE REVIEW

**Comment by jvine** [comment]
The grey menu bar should have the same inner container width as the red banner (and white banner, and content, etc.)

There's an outer div that creates the row, then an inner div that constrains the width of the content within that row. So Library services shd be left aligned with SearchWorks; Selections shd be right aligned with Feedback.

**Comment by jvine** [comment]
Somewhere in the css there is this:
`.dropdown-toggle:focus {
     outline: 0; 
}`
which is what's causing the focus indicator to not appear on the search toggle and Library services etc.  Don't know why it's there or what else it might affect... (remove it and see?)

**Comment by jvine** [comment]
White flash has to do with this:
```
.nav .open>a, .nav .open>a:hover, .nav .open>a:focus {
    background-color: #eeeeee;
    border-color: #000000;
```
border-color is already overridden by `#search-subnavbar-container .navbar-nav>li a `- if you add ` background-color: inherit;` to that class, it should kill the white.

**Comment by drh-stanford** [comment]
@jvine Great! Thanks for the pointers. I've corrected the tab focus and white flashes in a7f12c0

**Comment by jvine** [comment]
The inner and outer container naming has gotten confusing.

The outer container (currently #search-subnavbar) should:
- have the color, height, and shadow styling (which is currently attached to the inner container)
- be added to lists that contain these IDs:
`#outer-container, #topnav-container, #search-navbar-container, #sul-footer-container`

The inner container (currently #search-subnavbar-container) should:
- NOT have the color, height, shadow styling
- be added to lists that contain these IDs:
`#topnav, #search-navbar, #main-container, #sul-footer, #masthead-container`
including the `@media` width settings.

**Comment by jkeck** [comment]
@jvine did I accomplish that w/ 56d13116f3e4a67b7b169238e9fa0fd92d3d09d1?  I can redeploy for you to take a look.

subnav

I'm pointing out a bit of padding that still remains which has to do w/ the collapse behavior (so we should prob. tackle it as part of #1408)

**Comment by jvine** [comment]
Yeah, it looks like you did.

**Comment by drh-stanford** [comment]
Great! Thanks! That bug was driving me insane

**Pull request merged**
