### PR TITLE
Update availability display on record view to match the search…

### LINKED ISSUE #1135: Align display of availability on results & record view (was Users don't understand the meaning of the availability icons on record view)
Display the call number list & availability info on the record view in a table layout, like on the results view.

On the record view, the location name, stackmap link, MHLD info, and location-level request button will be outside (above) the table. Only the items for the location are in table layout. It might be best to take everything out of the ul markup, I'm not sure. Something like this:

```
<h4 class="location-name">Stacks</h4>
<a class="stackmap-find-it"><i class="fa fa-map-marker"></i> Find it</a>
<div class="mhld note-highlight">Latest...</div>
<div class="mhld">Library has...</div>
<table>
   <caption class="sr-only">Items in Stacks</caption>
   <thead>
      <tr class="sr-only">
         <th scope="col">Call number</th>
         <th scope="col">Status</th>
      </tr>
   </thead>
   <tbody>
         exactly like results view
   </tbody>
</table>
```

screen shot 2015-12-16 at 1 16 25 pm

Some additional details:
- [ ] hide the status text if there is current location text - same effect as for Due (date)
- [ ] would be nice to suppress the repetition of "Shelved by title" text for SHELBYTITL items, but I think this involves indexing
- [ ] CSS tweaks - below is what I modified to make it look like the screenshot - most of this could be applied to the results view as well.

```
table.availability td.indent-callnumber {padding: 0;}
#documents table.availability td.indent-callnumber {padding-left: 10px;}

table.availability td {border: 0; padding: 0;}

table.availability tr {border-bottom: 7px solid transparent;}

table.availability td {width: 50%;}

.availability .availability-icon {width: 18px; text-align: center;}

.table-condensed>thead>tr>th, .table-condensed>thead>tr>td, .table-condensed>tbody>tr>th, .table-condensed>tbody>tr>td, .table-condensed>tfoot>tr>th, .table-condensed>tfoot>tr>td {padding: 0 0 2px 0; line-height: 22px;}

.availability .status-text, .availability .current-location {margin-right: 0; font-size: 12px;}

table.availability {margin-top: 10px; margin-bottom: 0;}

table.availability thead tr th, table.availability thead tr td, table.availability tbody tr th, table.availability tbody tr td, table.availability tfoot tr th, table.availability tfoot tr td
{border-top: 0;}
```

### PR DESCRIPTION
**Pull request by jkeck**
…results closer.

Closes #1135 

## Examples
availability-1

availability-2

### 9943560 (before)
9943560-before

### 9943560 (after)
9943560-after

### CODE REVIEW

**Comment by jkeck** [comment]
@jvine I wonder if we should add a few px top-margin to the table on the record view as well (see `Find it` and `Request` links in the examples above).

**Comment by jvine** [comment]
@jkeck Agree, 2px?

**Comment by jkeck** [comment]
4px
top-margin

**Comment by jvine** [comment]
:+1:

**Comment by jkeck** [comment]
Moved Public Note:
10245940-public-note

**Comment by jvine** [comment]
:+1:  from me on latest change.

**Comment by jkeck** [comment]
## 7807994 (7d8f881)
### Before
7807994-before

### After
7807994-after

**Comment by jvine** [comment]
:+1:

**Comment by ndushay** [comment]
I say :+1: to merge, but perhaps @aeschylus or @peetucket could weigh in as I am out of my comfort zone.

**Comment by peetucket** [comment]
Looks fine to me.

**Pull request merged**
