### PR TITLE
fix css to truncate locations and display locations inline

### LINKED ISSUE #3791: Location lists in index view are not truncated
This query will show the issue: https://searchworks.stanford.edu/?f%5Bbuilding_facet%5D%5B%5D=Philosophy+%28Tanner%29&f%5Bbuilding_facet%5D%5B%5D=SAL3+%28off-campus+storage%29&f%5Bbuilding_facet%5D%5B%5D=Education+%28Cubberley%29

Current display:
Screenshot 2024-01-24 at 2 56 16 PM

What we expect:
Screenshot 2024-01-24 at 2 57 39 PM

Likely related to: https://github.com/sul-dlss/SearchWorks/pull/3756

### PR DESCRIPTION
**Pull request by dnoneill**
closes #3791 

Screenshot 2024-01-24 at 3 54 11 PM

### CODE REVIEW

**Review by corylown — CHANGES_REQUESTED** [review]
@dnoneill this fixes the truncation issue but changes the layout when "Check availability" is expanded to show the location/availability table.

This PR:
Screenshot 2024-01-24 at 4 12 34 PM

Expected layout when Check availability is expanded:
Screenshot 2024-01-24 at 4 12 28 PM

**Comment by dnoneill** [comment]
@corylown Can I change the <span> tag to <div>? Would you prefer I wrap the <button> and <span> snippet into a div?

 https://github.com/sul-dlss/SearchWorks/blob/main/app/views/catalog/_accordion_section_library.html.erb#L14-L16

**Comment by corylown** [comment]
@dnoneill what you have proposed in https://github.com/sul-dlss/SearchWorks/pull/new/3791-css-truncate-2 looks good to me.

**Comment by dnoneill** [comment]
@corylown Updated this branch to reflect -2 branch.

**Review by corylown — APPROVED** [review]

**Pull request merged**
