### PR TITLE
Exclusively use FOLIO circ rules to render location-level request links

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by cbeer** [comment]
With [#1610](https://github.com/sul-dlss/sul-requests/pull/1610) ready to go, I think we're ready to use FOLIO request rules to drive location request links in both Searchworks + sul-requests and see what happens.

**Comment by jcoyne** [comment]
@cbeer needs a rebase.

**Comment by jcoyne** [comment]
@cbeer does this relate to #3129 ?

**Comment by cbeer** [comment]
It's related to #3129, but does nothing to address the outstanding TODOs on that ticket. This basically cleans up a little more  hard-coded library + location data now that the aeon data is available on the FOLIO location objects.

**Review by jcoyne — APPROVED** [review]

**Pull request merged**
