### PR TITLE
Configure the sms tool action

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Review by corylown — CHANGES_REQUESTED** [review]
This fixes the issue, but the after-submit display is broken both in Firefox and Chrome:
Screen Shot 2022-08-23 at 9 13 59 AM

**Comment by cbeer** [comment]
😬

**Comment by corylown** [comment]
There is something oddly pleasing about the glitch though :-)

**Comment by cbeer** [comment]
76884f4 ought to do it. I'm not sure why those `_success` templates wandered off, but Blacklight 6 -> 7 changed some stuff about the modal markup and it's incompatible with the ajax_modal.js we copied over from Blacklight 6 🤷‍♂️

**Review by corylown — APPROVED** [review]

**Pull request merged**
