### PR TITLE
Course reserves are now driven from the Folio data

### PR DESCRIPTION
**Pull request by jcoyne**
Ref #3736

### CODE REVIEW

**Comment by hudajkhan** [comment]
Trying this out locally and on staging, the number of courses on the reserves page with FOLIO is 687 while it is 503 in current production. This isn't an error, but just making a note.  

_When clicking on an individual course reserve link_
Current production: 
Screenshot 2024-02-16 at 1 13 58 PM

Staging with branch:
Screenshot 2024-02-16 at 1 15 05 PM

Also of note, in production, the URL also includes the instructor facet "&f[instructor][]=Alexander+Nemerov" whereas staging has just the course number. (This may also be fine. Just noting the difference)

In staging, the course reserve red button does not seem to be visible in the search results view as it is in production. 

_When clicking on item_
Current production:
Screenshot 2024-02-16 at 1 17 21 PM

Staging with branch:
Screenshot 2024-02-16 at 1 17 49 PM

**Comment by hudajkhan** [comment]
Noting a few more differences (these aren't necessarily errors, just differences):

- The facet label for courses changed in this PR from "course" to "courses_folio_id_ssim" . It may be useful for consistency to keep the same label, but that can be up for discussion. 
- In the example above, the ordering of the courses in an individual page "course reserves" box is different between staging and production, but the same set is represented in both places.  This may be a minor difference.  In production, in the example above, it seems the list is ordered alphabetically by course number.

**Comment by jcoyne** [comment]
@hudajkhan I believe the missing red button is because we need this config change to be deployed: https://github.com/sul-dlss/sul-solr-configs/pull/310

Aside from that I believe all the changes were intentional.

**Comment by jcoyne** [comment]
@dbranchini @saseestone can you speak about what we want to do with the course reserve panel? 
Huda correctly pointed out we don't have it sorted by course name, however, in this case this is a single cross listed course. (course listing 46f8e5a3-a407-4277-9cfc-ce9ab0307c8b).  Is there some change we want to make to visualize this cross-lising?
Screenshot 2024-02-16 at 3 32 20 PM

**Comment by cbeer** [comment]
I've deployed the solrconfig changes (after figuring out that we were using a special Argo branch of sul-solr-configs....).

I'm pretty sure we don't want to use the facet label "Courses (FOLIO)". Our patrons don't know what FOLIO is. @dbranchini ?

**Comment by jcoyne** [comment]
@hudajkhan it's now sorted by course number:

Screenshot 2024-02-21 at 1 41 13 PM

**Pull request merged**
