### PR TITLE
Styling changes for identity / accessibility

### LINKED ISSUE #1731: Update some styles/colours for identity / accessibility
### Basic link treatment
Should change all the basic black dotted-underline links; special white, red etc. links should remain unchanged. 
```
a {
color: #006CB8;
text-decoration: none;
border-bottom: none;
}
a:hover, a:focus, a:active {
color: #00548f;
text-decoration: underline;
border-bottom: none;
}
#topnav .header-links a {text-decoration: none;} 
^ add this else the header links get two underlines on hover 
```
before
screen shot 2017-09-08 at 12 29 22 pm
after
screen shot 2017-09-08 at 12 28 37 pm
screen shot 2017-09-08 at 12 28 55 pm

### Background colour
Change subnav bar colour for more contrast and consistency.
```
#search-subnavbar-container, #search-subnavbar-container .dropdown-menu {
    background-color: #797268;}
#search-subnavbar-container .navbar-nav>li a {
    background-color: transparent;}
^ set to same colour as navbar or to transparent to avoid the white flash on hover
```

### Update h2 heading colours
With the added blue links, the red headings are too much colour on the page and don't add meaning. 

`h2, .facets.sidenav .top-panel-heading h2 {color: #544948;}`

### PR DESCRIPTION
**Pull request by camillevilla**
Closes #1731 

This PR changes:
- base link styles (including `a:hover`, `a:active`, `a:focus`)
- changes sidebar `<h2>` from red to smoke
- increases contrast on the subnavbar
- increases services menu font size

### Before
styling_before

### After
styling_after

### Before
menu_before

### After
menu_after

### CODE REVIEW

**Comment by camillevilla** [comment]
hi @jvine! let me know if a screenhero walkthrough is in order.

**Comment by jvine** [comment]
Yes, screenhero please @camillevilla . ready when you are.

**Comment by camillevilla** [comment]
Received feedback from @jvine and made the following changes:
- [ ] changed the base h2 color to `$smoke`
- [ ] increase library services menu font to `16px` / `1.6rem`

**Comment by jkeck** [comment]
Coveralls doesn't test css anyway, so I'm shipping even though they are stuck.

**Pull request merged**
