### PR TITLE
float-right for preview document-thumbnails

### LINKED ISSUE #1358: Gallery view cover image should be float:right
screen shot 2017-06-15 at 9 50 06 am

prod has:
```
.document-thumbnail {
    margin-bottom: 0;
}

application-7d7d312….css:12
.document-thumbnail {
    float: right;
    padding-left: 20px;
    margin-bottom: 20px;
}
```

stage has
```
.document-thumbnail {
    margin-bottom: 0;
}
```

### PR DESCRIPTION
**Pull request by drh-stanford**
This PR fixes #1358.

### After

screen shot 2017-06-15 at 3 30 22 pm
screen shot 2017-06-15 at 3 30 41 pm

### CODE REVIEW

**Comment by jkeck** [comment]
Hmm, I _think_ @jvine meant that they should be `float: right`, not `float: left`.

## Current production
prod

## This PR
branch

**Comment by jvine** [comment]
Apologies. It said "right" right in front of me, too. sigh.

**Comment by drh-stanford** [comment]
Ok, I changed it to float: right with left padding.

**Comment by drh-stanford** [comment]
Also, when the item doesn't have an image, it omits it in the preview pane. I'm assuming that's correct behavior? See screenshot:

screen shot 2017-06-15 at 3 33 29 pm

**Comment by jvine** [comment]
@drh-stanford that's completely logical, but it's not what i observed IRL this morning.

**Comment by drh-stanford** [comment]
weird -- i'm not seeing that behavior anymore -- it must of been something wrong with my local instance 

screen shot 2017-06-15 at 3 53 42 pm

**Pull request merged**
