### PR TITLE
Underline links that appear in text

### LINKED ISSUE #3779: Links are not clearly identifiable - Body text/links (Accessibility)
Color alone is not enough to distinguish a link from the surrounding text.

[SiteImprove Issue with details](https://my2.siteimprove.com/Accessibility/1059585/NextGen/Issue/1?ruleId=62&pageSegments=&issueKind=1&exceptTags=1,2&conformance=&siteTargetIssueKinds=1,2&wcagVersion=21&siteTarget.wcagVersion=21&siteTarget.conformanceLevels=0,1,3,4&siteTarget.issueKinds=1,2&siteTarget.wcagVersion=21&siteTarget.conformanceLevels=0,1,3,4&siteTarget.issueKinds=1,2
)

Note that on [this page](https://searchworks.stanford.edu/), it's only calling out two links even though there are several links on this page. Headings seem to be excluded, but what about the facet links? 

**To-do's**
- [x] @dbranchini: Clarify how to address. 

**Solution**
Adding an underline is a possible solution.

### LINKED ISSUE #3818: Use text-underline-offset for decorating links
Currently Searchworks uses border-bottom for decorating links, which is likely just an outdated hack for getting the underline further away from the text to not interfere with descenders. The use of border bottom makes our styles way more complex that they need to be as this causes some positioning changes.

### PR DESCRIPTION
**Pull request by jcoyne**
Using color alone is not enough for accessability.

Fixes #3818
Fixes #3779

### CODE REVIEW

**Comment by cbeer** [comment]
- [ ] I'm not seeing any underlining in Safari.

- [ ] The search subnav's hover behavior changed from
Screenshot 2024-02-08 at 12 45 46
to
Screenshot 2024-02-08 at 12 46 00

- [ ] it feels like there's an inconsistency on the home page where the feature resource card titles have the underscore but "Search Stanford's library resources" don't. 
Screenshot 2024-02-08 at 12 55 20

- [ ] should the topic overview headers in articles+ have the underscore style?
Screenshot 2024-02-08 at 12 51 47

- [ ] I don't think the checkbox labels for articles+ need the underscore style?
Screenshot 2024-02-08 at 12 52 01

- [ ] Is it weird that "more" and "view larger" links in the facets are underscored but not the facet values?
Screenshot 2024-02-08 at 12 56 36

- [ ] Should selected database titles have the underscore style?
Screenshot 2024-02-08 at 12 57 09

- [ ] Presumably the hierarchical student work facet  or call number facet shouldn't have underscores 
Screenshot 2024-02-08 at 12 58 06

Screenshot 2024-02-08 at 12 58 38

- [ ] Record titles in the header of the preview (from browse or search results brief/gallery views) shouldn't have underscoring?
Screenshot 2024-02-08 at 13 01 10

**Comment by dbranchini** [comment]
Thank you @cbeer, at least one of these appears to be different in different browsers. Because the second one looked different in Chrome for me, I went one by one. Generally, I agree with Chris's comments above. 

1. Nav bar links - I see the same thing in both FF and Chrome.
2. Featured resource card titles - no underline (I don't see it Chrome, but see it in FF.)
3. Topic headers - not sure how to see this, but headers should NOT have an underline
4. Search Settings - I agree with Chris, no underline
5. More/view larger - I agree, no underline
6. Database titles - not sure how to see this, but headers should NOT have an underline
7. Facets -no underline for any facets, seems to be happening on the hierarchical ones
8. Record titles - no underline for any headings 
9. Flash message icon button close - no underline
10. Placeholder cover images - I agree, no underline

**Comment by dbranchini** [comment]
Shouldn't be any underlines on this dropdown:


There's a significant difference b/n PURL dotted underlines and these underlines. It's due to the different style definitions. PURL uses border-bottom: 1px dotted [gray var], and SW uses text decoration. It's not very apparent until you see it with a larger font size (just under 16 px). Please take a look at the screens side by side. PURL is more subtle, even with the darker gray used by Justin for SW (I replaced it on this screenshot). I prefer the PURL handling. 



Unfortunately, I forgot to capture the URL for this next one, but note that the underlines are still getting picked up for some headings. Headings that are links shouldn't be underlined.

**Comment by dbranchini** [comment]
Looks great - and ready for production! Thank you, @jcoyne !

**Comment by cbeer** [comment]
Did you want underlining in menus?
Screenshot 2024-02-12 at 10 08 19

**Comment by jcoyne** [comment]
@cbeer I think we still do want to retain the underline on the "Help" and "Selections" dropdowns, but not on the "Send to" one, right?

**Comment by cbeer** [comment]
It looks like pagination links now have an underscore style on hover?

Screenshot 2024-02-13 at 10 22 01

**Comment by cbeer** [comment]
I'm also seeing gallery view tiles with the underline style:

Screenshot 2024-02-13 at 10 22 44

**Comment by cbeer** [comment]
@dbranchini : Does it make sense that the zoom buttons in stack maps have the underline styling?

Screenshot 2024-02-13 at 10 28 27

**Comment by cbeer** [comment]
The "At the library" header seems like it has the underline style:

Screenshot 2024-02-13 at 10 29 58

**Comment by cbeer** [comment]
In chrome, the dotted underscore for the "At the library" section is... pretty big:

Screenshot 2024-02-13 at 10 30 59

**Comment by dbranchini** [comment]
> Did you want underlining in menus? Screenshot 2024-02-12 at 10 08 19

No

**Comment by jcoyne** [comment]
@corylown That issue is in https://github.com/sul-dlss/SearchWorks/pull/3960

**Pull request merged**
