### PR TITLE
update css for gallery view to responsively fit screen

### LINKED ISSUE #3894: Preview in gallery is odd on rows of three or two
It seems to only work for rows of 4

Screenshot 2024-02-06 at 4 31 08 PM
Screenshot 2024-02-06 at 4 30 27 PM

### PR DESCRIPTION
**Pull request by dnoneill**
closes #3894 
View ticket to see current view. See screenshots below for updated view.

Screenshot 2024-02-29 at 4 44 28 PM
Screenshot 2024-02-29 at 4 44 18 PM
Screenshot 2024-02-29 at 4 44 04 PM

### CODE REVIEW

**Comment by jcoyne** [comment]
@dnoneill can you add some screenshots with the preview open on a card in 2 and 3 column layouts?

**Comment by dnoneill** [comment]
@jcoyne thanks for the catch, the margins are off. The  I also noticed a weird thing if you have preview open and resize the screen it does not show up where you expect. This is also happening on production.

Screenshot 2024-02-28 at 1 28 20 PM
Screenshot 2024-02-28 at 1 27 59 PM

**Comment by jcoyne** [comment]
I'm seeing this behavior @dnoneill where some items get very big and the preview is way down the page, rather than right below.
Screenshot 2024-02-28 at 12 42 44 PM

**Comment by dnoneill** [comment]
@jcoyne yup, that is what I am seeing. That is also happening on production so it is not technically part of this PR but we might want to fix it on this pr or we might want to split it off. I am not sure about that.

**Comment by jcoyne** [comment]
@dnoneill  That is the problem that #3894 was trying to solve.

**Comment by dnoneill** [comment]
Wow. My bad. Can't believe I missed that. I thought it was all the extra padding displaying in the right on gallery view. Do we want to fix that as well?

**Comment by dnoneill** [comment]
Updated views in main comment. This ticket should be ready to review. Sorry about the confusion.

**Review by jcoyne — APPROVED** [review]

**Pull request merged**
