### PR TITLE
responsive behavior for redesigned banner

### LINKED ISSUE #1408: Mobile collapse of banner
Depends on #1410.

### mobile collapse
- [x] white topnav stays the same
- [x] red banner remains 100px and stacks logo and target selector above the search box
- [x] grey navbar remains 35px and collapses all its menu items into one
screen shot 2017-06-23 at 4 34 54 pm

### PR DESCRIPTION
**Pull request by camillevilla**
Closes #1408

## Todos:

- [x] Clean up SCSS
- [x] fine tune distance btwn Searchworks logo and dropdown
- [x] input form should flow left
- [x] fix left padding on Library Services
- [x] override width issues with Bootstrap's `input-group-btn`
- [x] write a feature test for responsive behavior

## Demo
responsive_navbars

### CODE REVIEW

**Comment by camillevilla** [comment]
@jvine I didn't make too many changes beyond what we discussed last week but I'd appreciate a quick look over the SCSS changes. Major changes in this PR include:
- moving all subnavbar styles to their own stylesheet
- small Rubocop style guide fixes (alphabetical properties, changing `0px` to `0`, etc.)

**Comment by jvine** [comment]
A couple of things:
- Library services is still indented at the widest width - it should be left aligned with the SUL logo, SearchWorks, and facets
- when you toggle the Library services and Selections items within the collapsed navbar menu, they rotate the Menu icon - only toggling Menu itself should do this 

Behaviour of logo/target dropdown and search box looks good.

**Comment by camillevilla** [comment]
@jvine I fixed the Library services padding, but I'm getting lost in the weeds with the rotating icon. Could I split it into another ticket? I'm looking back at the production app and it looks like the nested dropdowns were acting funny there too. 

navbar_rotate_bug


I have an idea for a JS fix but I'd want to talk to @jkeck about whether we should keep using this [jQuery plugin](https://github.com/sul-dlss/SearchWorks/blob/master/app/assets/javascripts/jquery.rotatehelper.js) for rotating the icons.

**Comment by jvine** [comment]
@camillevilla yes! get out of the weeds! quick!

**Pull request merged**
