### PR TITLE
Refactor LocationRequestLinkComponent to avoid passing items

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Review by marlo-longley — CHANGES_REQUESTED** [review]
This branch breaks the button content for me locally

Screenshot 2024-02-22 at 1 50 17 PM

**Comment by marlo-longley** [comment]
@jcoyne refactoring this reference to `@library` fixed the error above:
https://github.com/sul-dlss/SearchWorks/blob/ca62b81660681e582eb5326b2fb4db4095767ee8/app/components/location_request_link_component.rb#L72

**Comment by jcoyne** [comment]
@marlo-longley thanks!  Stupid ivars never tell you when you use one that hasn't been declared!

**Review by marlo-longley — APPROVED** [review]

**Comment by marlo-longley** [comment]
We can close this conflicting PR if merged https://github.com/sul-dlss/SearchWorks/pull/3980

**Pull request merged**
