### PR TITLE
[WIP] switch from Dejavu EL -> Condensed Book fixes #2167

### LINKED ISSUE #2167: Replace DejaVu Sans Extralight with DejaVu Sans Condensed Book
This font still seems to be the best choice for display of diacritics and ligatures for non-English languages, but the Extralight version was a poor choice for readability in the results view.

https://www.fontsquirrel.com/fonts/dejavu-sans

### LINKED ISSUE #2204: CSS update for new font
Please remove this:

`letter-spacing: -.03em;`

- [x] line 46
- [x] line 57

from app/assets/stylesheets/searchworks-mixins.scss

(The new font spacing is already close.)

### PR DESCRIPTION
**Pull request by mejackreed**
_**[WIP]** while we figure out some inconsistencies w/ some diacritics in particular browsers._  

Fixes #2167 
Closes #2204 

screen shot 2018-11-16 at 8 47 05 am
screen shot 2018-11-16 at 8 46 44 am

### CODE REVIEW

**Comment by cbeer** [comment]
I'm surprised how much smaller these font files are; spot-checking the SVG, it seems like it may not have the same codepoint coverage?

**Comment by mejackreed** [comment]
Yeah, I'm not exactly sure what this means from: https://www.fontsquirrel.com/fonts/dejavu-sans

screen shot 2018-11-16 at 10 36 57 am

**Comment by camillevilla** [comment]
These changes have been deployed to SW UAT for @jvine's review

**Comment by mejackreed** [comment]
Closing in favor of #2213

**Pull request closed without merging**
